export const brandPages = [
  {
    slug: 'medstar',
    name: 'Medstar',
    logo: '/Brands/medstar.jpg',
    relationship: 'LTE Own Brand',
    featured: true,
    specialty: 'Medical consumables, PPE, sterilization and routine clinical supply',
    title: 'Medstar medical supplies in Bahrain, backed directly by LTE',
    description:
      'Medstar is Leading Trading Est\'s own medical supply brand in Bahrain, covering gloves, PPE, sterilization packaging, wound care, patient identification and routine clinical consumables.',
    intro:
      'Medstar was developed around the requirements of repeat healthcare procurement: practical specifications, dependable availability and direct local accountability through Leading Trading Est. Bahrain buyers can source everyday medical and dental consumables through one LTE-backed brand relationship.',
    keywords:
      'Medstar Bahrain, Medstar medical supplies Bahrain, Medstar gloves Bahrain, Medstar PPE Bahrain, Medstar sterilization pouches, Medstar wound care, Leading Trading Est Medstar',
    searchQuery: 'Medstar',
    categoryLinks: [
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [
      { title: 'Examination gloves and PPE', body: 'Nitrile, vinyl and examination glove lines alongside face masks and routine protective supplies.' },
      { title: 'Sterilization workflow', body: 'Sterilization pouches, reels and chemical indicator strips for controlled clinical processing.' },
      { title: 'Wound care and bandaging', body: 'Gauze, cotton, crepe bandages, conforming bandages and supporting dressing materials.' },
      { title: 'Daily clinical consumables', body: 'Patient ID bands, IV cannula support, ultrasound gel, microbrushes and other repeat-use essentials.' },
    ],
    productTerms: [
      'Nitrile gloves', 'Vinyl gloves', 'Examination gloves', 'Face masks',
      'Sterilization pouches', 'Sterilization reels', 'Chemical indicator strips',
      'Gauze swabs', 'Cotton rolls', 'Elastic crepe bandages', 'Ultrasound gel', 'Patient ID bands',
    ],
    faqs: [
      { question: 'Is Medstar owned by Leading Trading Est?', answer: 'Yes. Medstar is an own brand of Leading Trading Est and is supported locally by the LTE team in Bahrain.' },
      { question: 'What Medstar products are available in Bahrain?', answer: 'The Medstar range includes examination gloves, PPE, sterilization packaging, wound care, bandaging and routine clinical consumables. Availability is confirmed through quotation.' },
      { question: 'How can Bahrain buyers request Medstar supplies?', answer: 'Buyers can search the LTE catalog for Medstar or send their quantities and specifications to Leading Trading Est for a quotation.' },
    ],
  },
  {
    slug: 'romsons',
    name: 'ROMSONS',
    logo: '/Brands/romsons.png',
    relationship: 'Sole Agent Support in Bahrain',
    specialty: 'Disposable medical devices and clinical consumables',
    title: 'ROMSONS disposable medical devices in Bahrain',
    description:
      'Leading Trading Est provides sole-agent support for ROMSONS in Bahrain, connecting hospitals and clinics with disposable medical devices, urology, airway, drainage and procedure supplies.',
    intro:
      'ROMSONS is positioned within LTE\'s medical and surgical portfolio for buyers who need specification-led disposable device sourcing and reliable local follow-up. LTE handles Bahrain enquiries, product matching, documentation and quotation coordination.',
    keywords: 'ROMSONS Bahrain, ROMSONS distributor Bahrain, ROMSONS sole agent Bahrain, disposable medical devices Bahrain, ROMSONS medical supplies',
    searchQuery: 'ROMSONS',
    categoryLinks: [
      { label: 'Anesthesia & Respiratory', path: '/categories/anesthesia-respiratory' },
      { label: 'Urology', path: '/categories/urology' },
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
    ],
    focusAreas: [
      { title: 'Airway and respiratory disposables', body: 'Procedure-focused respiratory, oxygen and airway supply enquiries for clinical environments.' },
      { title: 'Urology and drainage', body: 'Disposable urology, urine collection and drainage requirements matched by specification.' },
      { title: 'Infusion and procedure support', body: 'Clinical disposable devices for recurring hospital, clinic and treatment-room demand.' },
    ],
    productTerms: ['Disposable medical devices', 'Urology supplies', 'Drainage products', 'Respiratory disposables', 'Clinical procedure consumables'],
    faqs: [
      { question: 'Who supports ROMSONS in Bahrain?', answer: 'Leading Trading Est provides sole-agent support for ROMSONS enquiries in Bahrain.' },
      { question: 'Can LTE quote ROMSONS products by specification?', answer: 'Yes. Buyers can share the ROMSONS item, reference, quantity or clinical requirement for product matching and quotation.' },
    ],
  },
  {
    slug: 'smi',
    name: 'SMI',
    logo: '/Brands/Smi.png',
    relationship: 'Sole Agent Support in Bahrain',
    specialty: 'Surgical sutures and wound closure',
    title: 'SMI surgical sutures and wound closure in Bahrain',
    description:
      'Leading Trading Est provides sole-agent support for SMI in Bahrain, including absorbable and non-absorbable surgical sutures for medical, dental and ophthalmic requirements.',
    intro:
      'SMI supports specification-sensitive wound closure across surgical disciplines. LTE helps Bahrain buyers identify suture material, structure, size, needle requirement and intended procedure before quotation.',
    keywords: 'SMI Bahrain, SMI sutures Bahrain, SMI distributor Bahrain, SMI sole agent Bahrain, surgical sutures Bahrain, wound closure supplies Bahrain',
    searchQuery: 'SMI',
    categoryLinks: [
      { label: 'Surgical Instruments', path: '/categories/surgical-instruments' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [
      { title: 'Absorbable sutures', body: 'Surgicryl PGA, 910, Rapid, Monofilament and Monofast options for procedure-specific selection.' },
      { title: 'Non-absorbable sutures', body: 'Nylon, polypropylene and braided silk lines supported by specification review.' },
      { title: 'Medical, dental and ophthalmic use', body: 'Quotation support based on material, gauge, needle profile, procedure and pack requirements.' },
    ],
    productTerms: ['Surgicryl PGA', 'Surgicryl 910', 'Surgicryl Rapid', 'Nylon sutures', 'Polypropylene sutures', 'Silk braided sutures'],
    faqs: [
      { question: 'Who supplies SMI sutures in Bahrain?', answer: 'Leading Trading Est provides sole-agent support for SMI suture enquiries in Bahrain.' },
      { question: 'Can LTE help identify the correct SMI suture?', answer: 'Yes. Share the suture material, size, needle profile, procedure or existing reference so the LTE team can support matching and quotation.' },
    ],
  },
  {
    slug: 'hermann-meditech', name: 'Hermann Meditech', logo: '/Brands/Hermann.png', relationship: 'Supported Brand Line',
    specialty: 'Precision surgical instruments', title: 'Hermann Meditech surgical instruments for Bahrain buyers',
    description: 'Hermann Meditech surgical instrument enquiries supported in Bahrain by Leading Trading Est with specification checks, quotation coordination and local follow-up.',
    intro: 'This brand line supports hospitals, clinics and specialist centers sourcing reusable surgical instruments where instrument type, dimensions, profile and intended procedure must be confirmed before ordering.',
    keywords: 'Hermann Meditech Bahrain, Hermann Meditech instruments, surgical instruments Bahrain, precision surgical tools Bahrain', searchQuery: 'Hermann Meditech',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }],
    focusAreas: [{ title: 'Precision instrument sourcing', body: 'Instrument selection based on procedure, dimensions, working end and handling requirements.' }, { title: 'Specification-led quotation', body: 'Support for item references, instrument schedules and specialist procurement lists.' }],
    productTerms: ['Surgical instruments', 'Reusable instruments', 'Procedure instruments', 'Instrument schedules'],
    faqs: [{ question: 'Can LTE quote Hermann Meditech instruments in Bahrain?', answer: 'Yes. Send the instrument name, reference, dimensions or schedule for specification review and quotation support.' }],
  },
  {
    slug: 'adc', name: 'ADC', logo: '/Brands/adc.png', relationship: 'Supported Brand Line',
    specialty: 'Stethoscopes, blood pressure and diagnostic devices', title: 'ADC diagnostic devices and stethoscopes in Bahrain',
    description: 'ADC diagnostic device enquiries in Bahrain through Leading Trading Est, including stethoscopes, blood pressure equipment and routine clinical diagnostics.',
    intro: 'ADC supports frontline diagnostic assessment. LTE connects Bahrain healthcare buyers with suitable diagnostic models and quotation support for clinics, hospitals and professional users.',
    keywords: 'ADC Bahrain, ADC stethoscope Bahrain, ADC blood pressure monitor Bahrain, diagnostic devices Bahrain', searchQuery: 'ADC',
    categoryLinks: [{ label: 'Diagnostic Devices', path: '/categories/diagnostic-devices' }, { label: 'Medical Equipment', path: '/categories/medical-equipment' }],
    focusAreas: [{ title: 'Clinical auscultation', body: 'Stethoscope enquiries for routine assessment and professional clinical use.' }, { title: 'Blood pressure diagnostics', body: 'Blood pressure equipment and related diagnostic requirements for care settings.' }],
    productTerms: ['ADC stethoscope', 'Blood pressure machine', 'Diagnostic equipment'],
    faqs: [{ question: 'Does LTE support ADC diagnostic devices in Bahrain?', answer: 'Yes. Leading Trading Est supports ADC product enquiries and quotations for Bahrain buyers.' }],
  },
  {
    slug: 'rogin-dental', name: 'Rogin Dental', logo: '/Brands/rogin.png', relationship: 'Supported Brand Line',
    specialty: 'Endodontic, restorative and dental supplies', title: 'Rogin Dental instruments and consumables in Bahrain',
    description: 'Rogin Dental supplies in Bahrain through Leading Trading Est, including endodontic files, burs, gutta percha, dental dam and specialist dental consumables.',
    intro: 'Rogin Dental covers a broad working range for dental practices, with particular depth across endodontic preparation, obturation, burs and supporting consumables.',
    keywords: 'Rogin Dental Bahrain, dental supplies Bahrain, endodontic files Bahrain, gutta percha Bahrain, dental burs Bahrain', searchQuery: 'Rogin Dental',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [{ title: 'Endodontic workflow', body: 'Files, reamers, reciprocating systems, gutta percha, paper points, spreaders and pluggers.' }, { title: 'Dental preparation', body: 'Carbide burs, diamond burs, polishing discs and supporting clinical consumables.' }],
    productTerms: ['Endodontic files', 'Gutta percha', 'Paper points', 'Dental burs', 'Dental dam', 'Surgical aspirator tips'],
    faqs: [{ question: 'What Rogin Dental products can LTE source?', answer: 'LTE supports enquiries for Rogin endodontic files, burs, gutta percha, paper points, dental dam and related specialist supplies.' }],
  },
  {
    slug: 'zogear', name: 'Zogear', logo: '/Brands/Zogear.png', relationship: 'Supported Brand Line',
    specialty: 'Dental consumables and practice essentials', title: 'Zogear dental consumables in Bahrain',
    description: 'Zogear dental consumables supplied in Bahrain through Leading Trading Est, including syringe tips, saliva ejectors, matrix bands and practice essentials.',
    intro: 'Zogear supports the recurring consumable needs of dental clinics. LTE provides local quotation and supply follow-up for practical chairside products.',
    keywords: 'Zogear Bahrain, Zogear dental supplies, dental consumables Bahrain, saliva ejector Bahrain, dental syringe tips Bahrain', searchQuery: 'Zogear',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [{ title: 'Chairside consumables', body: 'Air-water syringe tips, saliva ejectors, mixing pads and protective sleeves.' }, { title: 'Restorative support', body: 'Matrix bands, articulating paper and supporting dental practice items.' }],
    productTerms: ['Air water syringe tips', 'Saliva ejectors', 'Matrix bands', 'Articulating paper', 'Mixing pads'],
    faqs: [{ question: 'Can dental clinics request Zogear quotations from LTE?', answer: 'Yes. Clinics can send the product name, quantity and delivery requirement for local quotation support.' }],
  },
  {
    slug: 'optima-cast', name: 'Optima Cast', logo: '/Brands/optimacast.png', relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic fiberglass casting tape', title: 'Optima Cast orthopaedic casting tape in Bahrain',
    description: 'Optima Cast fiberglass orthopaedic casting tape enquiries in Bahrain through Leading Trading Est for hospitals, clinics and rehabilitation providers.',
    intro: 'Optima Cast is focused on lightweight fiberglass casting support. LTE handles Bahrain enquiries by size, color, quantity and clinical requirement.',
    keywords: 'Optima Cast Bahrain, orthopedic casting tape Bahrain, fibreglass cast tape Bahrain, orthopaedic supplies Bahrain', searchQuery: 'Optima Cast',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [{ title: 'Fiberglass casting', body: 'Lightweight casting tape for orthopaedic immobilization requirements.' }, { title: 'Size and quantity matching', body: 'Quotation support based on width, pack configuration, color and facility demand.' }],
    productTerms: ['Fiberglass casting tape', 'Orthopaedic cast tape', 'Casting supplies'],
    faqs: [{ question: 'Where can buyers request Optima Cast in Bahrain?', answer: 'Leading Trading Est supports Optima Cast enquiries and quotations for Bahrain healthcare buyers.' }],
  },
  {
    slug: 'osseous', name: 'Osseous', logo: '/Brands/osseous.png', relationship: 'Supported Brand Line',
    specialty: 'ENT surgical instruments', title: 'Osseous ENT instruments in Bahrain',
    description: 'Osseous ear, nose and throat instrument enquiries in Bahrain through Leading Trading Est with specialist specification and quotation support.',
    intro: 'Osseous supports ENT instrument requirements where working profile, size and procedure matter. LTE helps specialist centers and procurement teams submit precise enquiries.',
    keywords: 'Osseous Bahrain, ENT instruments Bahrain, ear nose throat instruments Bahrain, ENT surgical supplies Bahrain', searchQuery: 'Osseous',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }, { label: 'Medical Equipment', path: '/categories/medical-equipment' }],
    focusAreas: [{ title: 'ENT instrument sourcing', body: 'Ear, nose and throat surgical tools matched to specialist requirements.' }, { title: 'Reference-led procurement', body: 'Support for instrument references, dimensions and procedure schedules.' }],
    productTerms: ['ENT instruments', 'Ear instruments', 'Nasal instruments', 'Throat instruments'],
    faqs: [{ question: 'Can LTE support Osseous ENT instrument schedules?', answer: 'Yes. Buyers can submit an instrument schedule or reference list for review and quotation.' }],
  },
  {
    slug: 'berger', name: 'Berger', logo: '/Brands/berger.jpg', relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic supports, bracing and rehabilitation aids', title: 'Berger orthopaedic supports and braces in Bahrain',
    description: 'Berger orthopaedic supports, braces and rehabilitation aids in Bahrain through Leading Trading Est for clinical and recovery requirements.',
    intro: 'Berger supports mobility, stabilization and rehabilitation needs across neck, back, knee, arm and other orthopaedic applications.',
    keywords: 'Berger orthopaedic Bahrain, orthopedic braces Bahrain, knee support Bahrain, back support Bahrain, rehabilitation supplies Bahrain', searchQuery: 'Berger',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [{ title: 'Body supports and braces', body: 'Neck, back, knee, arm and shoulder support requirements.' }, { title: 'Rehabilitation aids', body: 'Support products selected by use, sizing and clinical recovery need.' }],
    productTerms: ['Knee supports', 'Back and spine supports', 'Arm supports', 'Neck supports', 'Finger splints'],
    faqs: [{ question: 'Does LTE supply Berger supports in Bahrain?', answer: 'LTE supports Berger orthopaedic and rehabilitation product enquiries for Bahrain buyers.' }],
  },
  {
    slug: 'bastos-viegas', name: 'Bastos Viegas', logo: '/Brands/bastosviegas.webp', relationship: 'Supported Brand Line',
    specialty: 'Surgical consumables, gauze, drapes and procedure sets', title: 'Bastos Viegas surgical consumables in Bahrain',
    description: 'Bastos Viegas surgical consumable enquiries in Bahrain through Leading Trading Est, including gauze, drapes and procedure-focused clinical sets.',
    intro: 'Bastos Viegas supports procedure preparation and sterile clinical workflows. LTE coordinates Bahrain quotations by product specification, pack and quantity.',
    keywords: 'Bastos Viegas Bahrain, surgical consumables Bahrain, surgical drapes Bahrain, medical gauze Bahrain, procedure sets Bahrain', searchQuery: 'Bastos Viegas',
    categoryLinks: [{ label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' }, { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' }],
    focusAreas: [{ title: 'Procedure preparation', body: 'Drapes, sets and supporting consumables for controlled clinical workflows.' }, { title: 'Gauze and wound care', body: 'Medical gauze and associated disposable requirements by size and pack.' }],
    productTerms: ['Surgical drapes', 'Medical gauze', 'Procedure sets', 'Surgical consumables'],
    faqs: [{ question: 'Can LTE quote Bastos Viegas consumables?', answer: 'Yes. Send the item reference, pack requirement and quantity for Bahrain quotation support.' }],
  },
];

export const brandRoutes = [
  { path: '/brands', changefreq: 'weekly', priority: '0.86' },
  ...brandPages.map((brand) => ({
    path: `/brands/${brand.slug}`,
    changefreq: brand.featured || ['romsons', 'smi'].includes(brand.slug) ? 'weekly' : 'monthly',
    priority: brand.featured ? '0.86' : ['romsons', 'smi'].includes(brand.slug) ? '0.82' : '0.74',
  })),
];

export const getBrandPage = (slug) => brandPages.find((brand) => brand.slug === slug);
