export const brandPages = [
  {
    slug: 'medstar',
    name: 'Medstar',
    logo: '/Brands/medstar.jpg',
    relationship: 'LTE Own Brand',
    featured: true,
    specialty: 'Proprietary wholesale consumables -- exclusive to Leading Trading Est Bahrain',
    title: 'Medstar brand proprietary wholesale consumables by LTE',
    description:
      'Medstar brand proprietary wholesale consumables by LTE. Medstar is Leading Trading Est\'s own medical supply brand in Bahrain -- the exclusive wholesale source for Medstar disposables, PPE, and infection-control consumables for hospitals and clinics.',
    intro:
      'Medstar brand proprietary wholesale consumables are developed and distributed exclusively by Leading Trading Est (LTE) in Bahrain. Buyers searching for Medstar consumables transact through LTE as the sole authorised channel -- not retail pharmacies or local clinics. Bulk pricing, MOH-compliant labelling, and verified Medstar batch documentation accompany every order. LTE supplies Medstar to hospitals, surgical centres, dental clinics, and procurement teams operating under NHRA-regulated supply chains.',
    keywords:
      'Medstar Bahrain, Medstar brand proprietary wholesale consumables by LTE, Medstar medical supplies Bahrain, Medstar consumables wholesale Bahrain, Leading Trading Est Medstar, Medstar PPE Bahrain, Medstar gloves Bahrain, Medstar distributor Bahrain, Medstar NHRA Bahrain',
    categoryLinks: [
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [
      {
        title: 'Exclusive wholesale channel -- not available through retail',
        body: 'Medstar brand proprietary wholesale consumables are supplied exclusively by LTE. Procurement teams and facilities require an LTE account to purchase Medstar product with verified traceability and NHRA-compliant documentation.',
      },
      {
        title: 'Broad Medstar consumable range for healthcare buyers',
        body: 'The Medstar catalogue through LTE covers nitrile, vinyl, and latex gloves; disposable syringes and needles; IV administration sets; wound care consumables; surgical drapes and gowns; face masks; and infection-control disposables for high-rotation healthcare procurement.',
      },
      {
        title: 'NHRA-compliant documentation with every Medstar order',
        body: 'All Medstar consumables supplied through Leading Trading Est carry NHRA import clearance, batch certification, and MOH-compliant product labelling. Procurement departments can request compliance documentation through the LTE quotation workflow.',
      },
    ],
    faqs: [
      { question: 'What is Medstar and who supplies it in Bahrain?', answer: 'Medstar is Leading Trading Est\'s proprietary wholesale consumable brand. LTE is the exclusive source for Medstar medical consumables in Bahrain -- not available through retail or secondary channels.' },
      { question: 'Are Medstar consumables NHRA approved in Bahrain?', answer: 'Yes. Medstar consumables supplied through LTE carry NHRA import clearance, batch documentation, and MOH-compliant labelling for institutional healthcare procurement.' },
      { question: 'How should buyers request Medstar supply?', answer: 'Send the product type, quantity, pack size, and intended use to Leading Trading Est. LTE will confirm availability, pricing, and documentation for the order.' },
    ],
  },
  {
    slug: 'romsons',
    name: 'Romsons',
    logo: '/Brands/romsons.png',
    relationship: 'Sole Agent -- Bahrain',
    specialty: 'Medical devices bulk sourcing -- catheters, IV therapy, respiratory, and hospital care',
    title: 'Romsons medical devices bulk sourcing Bahrain -- LTE sole agent',
    description:
      'Romsons medical devices bulk sourcing LTE. Leading Trading Est is the authorised Bahrain sole-agent for Romsons, supplying catheters, urine bags, IV sets, oxygen therapy, and hospital care products in wholesale volumes with NHRA import clearance.',
    intro:
      'Romsons medical devices bulk sourcing in Bahrain is handled exclusively through Leading Trading Est (LTE) as the authorised Bahrain sole-agent. Procurement officers at hospitals, clinics, and government health facilities transact through LTE as the direct importer with NHRA-cleared Romsons stock held in Sitra. No minimum order delays on stocked Romsons lines. Bulk pricing, tender support, and scheduled delivery coordination are managed by the LTE sales and accounts team.',
    keywords: 'Romsons Bahrain, Romsons medical devices bulk sourcing LTE, Romsons sole agent Bahrain, Romsons distributor Bahrain, Leading Trading Est Romsons, Romsons catheter Bahrain, Romsons urine bags Bahrain, Romsons IV sets Bahrain, Romsons hospital supplies Bahrain',
    categoryLinks: [
      { label: 'Urology', path: '/categories/urology' },
      { label: 'Anesthesia & Respiratory', path: '/categories/anesthesia-respiratory' },
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
      { label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' },
    ],
    focusAreas: [
      {
        title: 'LTE is the Bahrain sole-agent -- direct import, NHRA cleared',
        body: 'All Romsons products supplied through Leading Trading Est arrive as direct imports with NHRA Bahrain clearance and full manufacturer batch documentation. Procurement departments can request product regulatory files, traceability records, and approved vendor documentation from LTE.',
      },
      {
        title: 'Core Romsons bulk lines stocked at LTE Sitra',
        body: 'LTE maintains bulk inventory of Romsons Foley catheters, urine drainage bags, nasogastric and enteral feeding tubes, blood transfusion sets, paediatric burette sets, oxygen masks, nebuliser masks, adult care underpads, and neonatal care products.',
      },
      {
        title: 'Bulk pricing, standing orders, and tender support',
        body: 'LTE supports Romsons hospital procurement with wholesale pricing tiers, standing order agreements, and procurement schedule support for high-volume Bahrain facilities. Tender pricing and framework agreements are available through the LTE accounts team.',
      },
    ],
    faqs: [
      { question: 'Who is the Romsons sole agent in Bahrain?', answer: 'Leading Trading Est (LTE) is the authorised Bahrain sole-agent for Romsons medical devices. All Romsons procurement in Bahrain is directed through LTE.' },
      { question: 'What Romsons products does LTE stock in Bahrain?', answer: 'LTE stocks Romsons catheters, urine bags, feeding tubes, blood transfusion sets, burette sets, oxygen masks, underpads, neonatal care products, and IV therapy lines for bulk hospital supply.' },
      { question: 'Can hospitals buy Romsons in bulk from LTE?', answer: 'Yes. LTE supports Romsons bulk sourcing with wholesale pricing, standing orders, scheduled delivery, and tender framework support for Bahrain hospital procurement.' },
    ],
  },
  {
    slug: 'smi',
    name: 'SMI Sutures',
    logo: '/Brands/Smi.png',
    relationship: 'Exclusive Licensed Distributor -- Bahrain',
    specialty: 'Surgical sutures -- absorbable, non-absorbable, dental, and ophthalmic',
    title: 'SMI Sutures exclusive licensed distributor Bahrain -- LTE',
    description:
      'SMI Sutures exclusive licensed distributor Bahrain LTE. Leading Trading Est holds the exclusive Bahrain distribution licence for SMI AG surgical sutures -- absorbable, non-absorbable, dental, and ophthalmic sutures supplied with full NHRA clearance and ISO 13485 documentation.',
    intro:
      'SMI Sutures exclusive licensed distributor Bahrain LTE -- Leading Trading Est is the sole authorised channel for SMI AG surgical sutures in Bahrain. Operating theatres, surgical centres, government hospital procurement desks, and MOH-registered dental and ophthalmic facilities purchase SMI sutures through LTE. No secondary channels, no grey-market product. Sterility certification, shelf-life documentation, ISO 13485 compliance records, and NHRA Bahrain import clearance supplied with every order.',
    keywords: 'SMI Sutures Bahrain, SMI Sutures exclusive licensed distributor Bahrain LTE, SMI sutures distributor Bahrain, SMI surgical sutures Bahrain, Leading Trading Est SMI, SMI sole agent Bahrain, absorbable sutures Bahrain, non-absorbable sutures Bahrain, dental sutures Bahrain, ophthalmic sutures Bahrain',
    categoryLinks: [
      { label: 'Sutures', path: '/categories/sutures' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [
      {
        title: 'Exclusive licence: LTE is the only authorised SMI channel in Bahrain',
        body: 'LTE holds the exclusive Bahrain distribution licence for SMI AG sutures. There are no secondary SMI distributors or grey-market channels authorised in Bahrain. All institutional SMI suture procurement -- hospitals, clinics, dental centres, ophthalmic units -- must be directed through Leading Trading Est.',
      },
      {
        title: 'Full SMI suture portfolio: absorbable, non-absorbable, specialty',
        body: 'LTE supplies the complete SMI AG range: absorbable sutures (polyglycolic acid, chromic catgut, fast-absorbing plain gut), non-absorbable sutures (polypropylene, nylon, silk, polyester), dental sutures, ophthalmic sutures, and specialty wound-closure configurations across all USP sizes and needle profiles.',
      },
      {
        title: 'ISO 13485 and NHRA documentation on every SMI order',
        body: 'SMI sutures supplied through LTE include sterility certification, shelf-life records, CE mark documentation, ISO 13485 compliance files, and NHRA Bahrain import clearance. Tender submissions requiring regulatory documentation can be fulfilled through the LTE quotation workflow.',
      },
    ],
    faqs: [
      { question: 'Who is the exclusive SMI Sutures distributor in Bahrain?', answer: 'Leading Trading Est (LTE) holds the exclusive licensed distribution rights for SMI Sutures in Bahrain. All institutional SMI suture procurement should be directed to LTE.' },
      { question: 'What SMI suture types does LTE distribute in Bahrain?', answer: 'LTE distributes the full SMI AG range: absorbable (PGA, chromic catgut, plain gut), non-absorbable (polypropylene, nylon, silk, polyester), dental sutures, ophthalmic sutures, and specialty configurations.' },
      { question: 'What documentation comes with SMI sutures from LTE?', answer: 'All SMI orders from LTE include sterility certification, shelf-life documentation, ISO 13485 compliance records, CE mark files, and NHRA Bahrain import clearance.' },
      { question: 'How do I request an SMI Sutures quotation from LTE?', answer: 'Submit the suture material, USP size, needle profile, suture length, pack size, and quantity. LTE will confirm the SMI catalogue reference and prepare a quotation with full regulatory documentation.' },
    ],
  },
  {
    slug: 'hermann-meditech',
    name: 'Hermann Meditech',
    logo: '/Brands/Hermann.png',
    relationship: 'Supported Brand Line',
    specialty: 'Surgical instruments and procedure tools',
    title: 'Hermann Meditech surgical instruments in Bahrain',
    description: 'Hermann Meditech surgical instrument enquiries supported in Bahrain by Leading Trading Est with item-reference checks, instrument schedule review and quotation coordination.',
    intro: 'Hermann Meditech is handled by LTE as a surgical-instruments line. The page is focused on practical procurement: reusable instrument enquiries, item references, instrument schedules, procedure needs and Bahrain quotation follow-up through Leading Trading Est.',
    keywords: 'Hermann Meditech Bahrain, Hermann Meditech instruments Bahrain, surgical instruments Bahrain, procedure tools Bahrain',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }],
    focusAreas: [
      { title: 'Instrument sourcing', body: 'LTE positions Hermann Meditech for surgical instrument requirements where buyers need procedure tools and reusable instrument lines.' },
      { title: 'Instrument schedule review', body: 'Send instrument names, patterns, sizes, quantities, drawings, tender sheets or reference lists so LTE can review the requirement before quotation.' },
      { title: 'Procedure-led matching', body: 'Requests are handled by intended use, specialty, working end, material preference and packaging requirement instead of generic catalogue browsing.' },
      { title: 'Local quotation control', body: 'LTE manages Bahrain follow-up, commercial coordination and delivery planning for Hermann Meditech instrument enquiries.' },
    ],
    faqs: [
      { question: 'What does LTE support for Hermann Meditech?', answer: 'LTE supports Hermann Meditech surgical instrument enquiries, including individual items and full instrument schedules.' },
      { question: 'Can LTE quote Hermann Meditech instruments in Bahrain?', answer: 'Yes. Send the instrument name, reference, dimensions, pattern or full instrument schedule for review and quotation support.' },
    ],
  },
  {
    slug: 'adc',
    name: 'ADC',
    logo: '/Brands/adc.png',
    relationship: 'Supported Brand Line',
    specialty: 'Stethoscopes, blood pressure, thermometry, EENT and diagnostic tools',
    title: 'ADC diagnostic devices and stethoscopes in Bahrain',
    description: 'ADC diagnostic device enquiries in Bahrain through Leading Trading Est, including stethoscopes, blood pressure measurement, thermometry, EENT and routine diagnostic instruments.',
    intro: 'American Diagnostic Corporation presents a diagnostic portfolio covering blood pressure measurement, EENT diagnostic instruments, laryngoscopes, penlights, pulse oximeters, stethoscopes, thermometry and vital signs monitors. LTE supports Bahrain quotation handling for relevant ADC requirements.',
    keywords: 'ADC Bahrain, ADC stethoscope Bahrain, ADC blood pressure monitor Bahrain, diagnostic devices Bahrain, EENT instruments Bahrain',
    categoryLinks: [{ label: 'Diagnostic Devices', path: '/categories/diagnostic-devices' }, { label: 'Medical Equipment', path: '/categories/medical-equipment' }],
    focusAreas: [
      { title: 'Blood pressure measurement', body: 'ADC lists aneroid, digital, multicuff, clock, cuff and accessory categories for blood pressure measurement.' },
      { title: 'Stethoscopes and diagnostic instruments', body: 'ADC product families include stethoscopes, EENT instruments, penlights, pulse oximeters, thermometry and vital sign tools.' },
      { title: 'Professional care environments', body: 'ADC positions its tools for healthcare professionals and institutions, with diagnostic design and warranty support emphasized publicly.' },
    ],
    faqs: [{ question: 'Does LTE support ADC diagnostic devices in Bahrain?', answer: 'Yes. Leading Trading Est supports ADC product enquiries and quotations for Bahrain buyers.' }],
  },
  {
    slug: 'rogin-dental',
    name: 'Rogin Dental',
    logo: '/Brands/rogin.png',
    relationship: 'Supported Brand Line',
    specialty: 'Endodontic files, obturation, burs and restorative dental consumables',
    title: 'Rogin Dental endodontic and restorative supplies in Bahrain',
    description: 'Rogin Dental enquiries in Bahrain through Leading Trading Est, including endodontic files, gutta percha, paper points, burs, dental dam, polishing and root canal support products.',
    intro: 'The public Rogin Dental website is protected by bot verification, so LTE keeps this profile grounded in the actual Rogin Dental catalogue coverage available through Leading Trading Est. The line is strongest around endodontic preparation, obturation, canal retreatment, burs, polishing and supporting dental consumables for Bahrain clinics.',
    keywords: 'Rogin Dental Bahrain, Rogin Dental endodontic files Bahrain, Rogin Dental gutta percha Bahrain, Rogin Dental burs Bahrain, dental supplies Bahrain',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [
      { title: 'Endodontic file systems', body: 'LTE catalogue coverage includes Rogin Dental K-files, H-files, reamers, Recip-One, Sup-Taper, Super Flexi, retreatment files and INO-Shaper enquiries.' },
      { title: 'Obturation and root canal support', body: 'Rogin Dental requests can include absorbent paper points, gutta percha points, gutta percha cutters, paste carriers, pluggers and spreaders.' },
      { title: 'Burs, isolation and finishing', body: 'Dental practices can request Rogin Dental carbide burs, diamond burs, latex dental dam and polishing disc requirements through LTE.' },
      { title: 'Clinic procurement handling', body: 'LTE reviews Rogin Dental requirements by file type, ISO size, working length, taper, bur pattern, pack size, quantity and delivery need.' },
    ],
    faqs: [
      { question: 'What Rogin Dental products can LTE support?', answer: 'LTE supports Rogin Dental enquiries for endodontic files, reamers, gutta percha products, paper points, burs, dental dam, polishing discs and related dental consumables.' },
      { question: 'What details help with a Rogin Dental quotation?', answer: 'Send the product name, ISO size, working length, taper, bur shape, pack size, quantity or existing reference so LTE can confirm the quotation path.' },
    ],
  },
  {
    slug: 'zogear',
    name: 'Zogear',
    logo: '/Brands/Zogear.png',
    relationship: 'Supported Brand Line',
    specialty: 'Dental disposable, endodontic, orthodontic, rotary, laboratory and equipment categories',
    title: 'Zogear dental consumables in Bahrain',
    description: 'Zogear dental consumables supplied in Bahrain through Leading Trading Est, including disposable, endodontic, orthodontic, material, rotary, laboratory and equipment enquiries.',
    intro: 'Zogear presents itself as a dental product manufacturer and supplier with public product categories covering dental disposable, endodontic, dental material, orthodontic, dental rotary, dental laboratory, dental equipment, oral care and teeth model lines. LTE supports Bahrain dental buyers with quotation handling for relevant Zogear requirements.',
    keywords: 'Zogear Bahrain, Zogear dental supplies, dental disposable Bahrain, dental consumables Bahrain, dental equipment Bahrain',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [
      { title: 'Dental disposable and chairside supplies', body: 'Zogear public categories include dental disposable and oral care lines for routine clinic consumption.' },
      { title: 'Endodontic, rotary and material categories', body: 'The brand lists endodontic, dental material and dental rotary product groups for practice workflows.' },
      { title: 'Laboratory and equipment coverage', body: 'Zogear also presents dental laboratory, dental equipment and teeth model categories.' },
    ],
    faqs: [{ question: 'Can dental clinics request Zogear quotations from LTE?', answer: 'Yes. Clinics can send the product name, quantity and delivery requirement for local quotation support.' }],
  },
  {
    slug: 'optima-cast',
    name: 'Optima Cast',
    logo: '/Brands/optimacast.png',
    relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic casting tape',
    title: 'Optima Cast orthopaedic casting tape in Bahrain',
    description: 'Optima Cast orthopaedic casting tape enquiries in Bahrain through Leading Trading Est for hospitals, clinics and rehabilitation providers.',
    intro: 'Public crawlable official detail for Optima Cast is limited. LTE keeps this page focused on the orthopaedic casting supply role and quotation handling by size, pack, colour and intended clinical use.',
    keywords: 'Optima Cast Bahrain, orthopedic casting tape Bahrain, orthopaedic supplies Bahrain',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [
      { title: 'Casting tape enquiries', body: 'LTE reviews orthopaedic casting tape requirements by width, roll quantity, pack configuration and facility demand.' },
      { title: 'Orthopaedic supply route', body: 'Requests are connected to the LTE orthopaedic and rehabilitation category for Bahrain quotation support.' },
    ],
    faqs: [{ question: 'Where can buyers request Optima Cast in Bahrain?', answer: 'Leading Trading Est supports Optima Cast enquiries and quotations for Bahrain healthcare buyers.' }],
  },
  {
    slug: 'osseous',
    name: 'Osseous',
    logo: '/Brands/osseous.png',
    relationship: 'Supported Brand Line',
    specialty: 'ENT surgical instruments',
    title: 'Osseous ENT instruments in Bahrain',
    description: 'Osseous ear, nose and throat instrument enquiries in Bahrain through Leading Trading Est with specialist specification and quotation support.',
    intro: 'Public crawlable official detail for Osseous is limited. LTE keeps the profile focused on ENT instrument supply support, reference review and Bahrain procurement handling.',
    keywords: 'Osseous Bahrain, ENT instruments Bahrain, ear nose throat instruments Bahrain, ENT surgical supplies Bahrain',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }],
    focusAreas: [
      { title: 'ENT instrument schedules', body: 'LTE can review ENT instrument schedules by instrument name, reference, size and intended procedure.' },
      { title: 'Specialist quotation support', body: 'Requests are handled through LTE for local follow-up and quotation coordination.' },
    ],
    faqs: [{ question: 'Can LTE support Osseous ENT instrument schedules?', answer: 'Yes. Buyers can submit an instrument schedule or reference list for review and quotation.' }],
  },
  {
    slug: 'berger',
    name: 'Berger',
    logo: '/Brands/berger.jpg',
    relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic supports, braces, stockings, sports and comfort products',
    title: 'Berger orthopaedic supports, braces and medical stockings in Bahrain',
    description: 'Berger orthopaedic support enquiries in Bahrain through Leading Trading Est, including cervical collars, shoulder and arm supports, hand and wrist supports, trunk and lumbar support, finger splints, medical stockings, sports and kids support requirements.',
    intro: 'Berger Orthopedics presents its range around quality, comfort and performance, with washable fabrics, anatomical design and high-tech knitting. Its official product menu covers cervical collars, shoulder and arm, hand and wrist, trunk and lumbar region, ankle and foot, silicones, finger splints, elderly and disabled support, pillows and cushions, medical stockings, sports and kids lines. LTE connects that Berger portfolio to Bahrain quotation and procurement support.',
    keywords: 'Berger orthopaedic Bahrain, Berger braces Bahrain, Berger medical stockings Bahrain, Berger knee support Bahrain, Berger cervical collar Bahrain, orthopedic supports Bahrain',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [
      { title: 'Official body-region categories', body: 'Berger lists cervical collars, shoulder and arm, hand and wrist, trunk and lumbar, ankle and foot, finger splints and other support categories.' },
      { title: 'Comfort and material positioning', body: 'Berger emphasizes maximum wearing comfort and durability using fine materials, knitting technology and workmanship.' },
      { title: 'Medical stockings and daily wear', body: 'Berger includes medical stockings and products designed for use at home, at work and during sports.' },
      { title: 'LTE catalogue coverage', body: 'Current LTE coverage includes anti-embolism stockings, arm support, back and spine support, finger splints, kids neck and shoulder supports, knee support and neck support.' },
    ],
    faqs: [
      { question: 'What Berger products can LTE support?', answer: 'LTE supports Berger enquiries for anti-embolism stockings, arm supports, back and spine supports, finger splints, kids neck and shoulder supports, knee supports and neck supports.' },
      { question: 'What details are needed for a Berger quotation?', answer: 'Send the body area, size range, quantity, support level, intended use and any tender or clinic requirement so LTE can confirm the quotation path.' },
    ],
  },
  {
    slug: 'bastos-viegas',
    name: 'Bastos Viegas',
    logo: '/Brands/bastosviegas.webp',
    relationship: 'Supported Brand Line',
    specialty: 'Non-active medical devices and surgical consumables',
    title: 'Bastos Viegas surgical consumables in Bahrain',
    description: 'Bastos Viegas surgical consumable enquiries in Bahrain through Leading Trading Est, including non-active medical device and procedure consumable requirements.',
    intro: 'Bastos Viegas publicly describes itself as a Portuguese producer and supplier of non-active medical devices, with European production and distribution across more than 90 countries. LTE supports Bahrain buyers with quotation handling for relevant Bastos Viegas consumable requirements.',
    keywords: 'Bastos Viegas Bahrain, surgical consumables Bahrain, non active medical devices Bahrain, surgical drapes Bahrain, medical gauze Bahrain',
    categoryLinks: [{ label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' }, { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' }],
    focusAreas: [
      { title: 'Non-active medical devices', body: 'Bastos Viegas identifies its core production around non-active medical devices with European production standards.' },
      { title: 'International distribution background', body: 'The company states its products are distributed in more than 90 countries across six continents.' },
      { title: 'Procedure consumable support', body: 'LTE handles Bahrain enquiries by item reference, pack configuration, quantity and intended clinical workflow.' },
    ],
    faqs: [{ question: 'Can LTE quote Bastos Viegas consumables?', answer: 'Yes. Send the item reference, pack requirement and quantity for Bahrain quotation support.' }],
  },
];

export const brandRoutes = [
  { path: '/brands', changefreq: 'weekly', priority: '0.86' },
  ...brandPages.map((brand) => ({
    path: `/brands/${brand.slug}`,
    changefreq: brand.featured || ['romsons', 'smi'].includes(brand.slug) ? 'weekly' : 'monthly',
    priority: brand.featured ? '0.86' : ['romsons', 'smi'].includes(brand.slug) ? '0.82' : '0.74',
  })),
];

export const getBrandPage = (slug) => brandPages.find((brand) => brand.slug === slug);
