export const brandPages = [
  {
    slug: 'medstar',
    name: 'Medstar',
    logo: '/Brands/medstar.jpg',
    relationship: 'LTE Own Brand',
    featured: true,
    specialty: 'LTE-backed medical consumables and routine healthcare supply',
    title: 'Medstar medical supplies in Bahrain, backed directly by LTE',
    description:
      'Medstar is Leading Trading Est\'s own medical supply brand in Bahrain, built for dependable local supply, repeat procurement and practical healthcare purchasing support.',
    intro:
      'Medstar should be understood as an LTE-backed supply line rather than a separate external manufacturer profile. The page now keeps the message focused on local accountability, procurement continuity and direct quotation handling through Leading Trading Est.',
    keywords:
      'Medstar Bahrain, Medstar medical supplies Bahrain, Leading Trading Est Medstar, Medstar PPE Bahrain, Medstar healthcare supplies Bahrain',
    categoryLinks: [
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [],
    faqs: [
      { question: 'Is Medstar connected to Leading Trading Est?', answer: 'Yes. Medstar is presented as an LTE-backed own brand and is handled locally by Leading Trading Est in Bahrain.' },
      { question: 'How should buyers request Medstar supply?', answer: 'Buyers should send their requirement, quantity and intended use to Leading Trading Est for quotation and availability confirmation.' },
    ],
  },
  {
    slug: 'romsons',
    name: 'ROMSONS',
    logo: '/Brands/romsons.png',
    relationship: 'Sole Agent Support in Bahrain',
    specialty: 'Hospital care, catheters, urine bags, health care and personal protection',
    title: 'ROMSONS hospital care and disposable medical supplies in Bahrain',
    description:
      'Leading Trading Est provides Bahrain sole-agent support for ROMSONS enquiries across hospital care, catheters, urine bags, health care, personal protection and related medical supply requirements.',
    intro:
      'ROMSONS presents itself as a long-established medical and healthcare brand with manufacturing experience and product categories that include hospital care, catheters and urine bags, health care, ortho care and personal protection. LTE connects those brand categories to Bahrain procurement, quotation and local follow-up.',
    keywords: 'ROMSONS Bahrain, ROMSONS sole agent Bahrain, ROMSONS hospital care Bahrain, ROMSONS catheter Bahrain, ROMSONS urine bags Bahrain, ROMSONS medical supplies',
    categoryLinks: [
      { label: 'Urology', path: '/categories/urology' },
      { label: 'Anesthesia & Respiratory', path: '/categories/anesthesia-respiratory' },
      { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' },
      { label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' },
    ],
    focusAreas: [
      { title: 'Hospital care and patient support', body: 'ROMSONS public categories include hospital care and health care products, suited to structured hospital and clinic procurement enquiries.' },
      { title: 'Catheters and urine bags', body: 'The brand highlights catheters, urine bags and related urology care categories, which LTE maps to Bahrain urology supply requirements.' },
      { title: 'Personal protection and care products', body: 'ROMSONS lists face masks, surgical hand gloves, underpads, adult care and related protection categories for routine healthcare supply.' },
    ],
    faqs: [
      { question: 'Who supports ROMSONS enquiries in Bahrain?', answer: 'Leading Trading Est provides Bahrain sole-agent support for ROMSONS enquiries and quotation follow-up.' },
      { question: 'What ROMSONS categories can LTE handle?', answer: 'LTE can handle enquiries for ROMSONS hospital care, urology, catheters, urine bags, personal protection, health care and related supply categories.' },
    ],
  },
  {
    slug: 'smi',
    name: 'SMI',
    logo: '/Brands/Smi.png',
    relationship: 'Sole Agent Support in Bahrain',
    specialty: 'Surgical sutures for medical, dental, ophthalmic and veterinary use',
    title: 'SMI surgical sutures and wound closure in Bahrain',
    description:
      'Leading Trading Est provides Bahrain sole-agent support for SMI surgical sutures, including absorbable and non-absorbable options for medical, dental and ophthalmic requirements.',
    intro:
      'SMI AG is a Belgian surgical suture manufacturer established in 1987. Its official portfolio is organized across medical, dental, ophthalmic and veterinary use, with absorbable, non-absorbable and specialty suture ranges. LTE supports Bahrain buyers with specification-led SMI quotation handling.',
    keywords: 'SMI Bahrain, SMI sutures Bahrain, SMI sole agent Bahrain, surgical sutures Bahrain, dental sutures Bahrain, ophthalmic sutures Bahrain',
    categoryLinks: [
      { label: 'Sutures', path: '/categories/sutures' },
      { label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' },
      { label: 'Dental Supplies', path: '/categories/dental' },
    ],
    focusAreas: [
      { title: 'Medical and surgical sutures', body: 'SMI organizes its medical range around absorbable sutures, non-absorbable sutures and specialty products.' },
      { title: 'Dental and ophthalmic sutures', body: 'SMI lists specialized dental sutures and ophthalmic sutures for procedure-specific requirements.' },
      { title: 'Quality and export background', body: 'SMI states EN ISO 13485 compliance and exports to a large international market from Belgium.' },
    ],
    faqs: [
      { question: 'Who supplies SMI sutures in Bahrain?', answer: 'Leading Trading Est provides Bahrain sole-agent support for SMI suture enquiries.' },
      { question: 'What information is needed for an SMI quotation?', answer: 'Send the suture material, size, needle profile, specialty area, quantity or existing reference so LTE can confirm the correct quotation path.' },
    ],
  },
  {
    slug: 'hermann-meditech',
    name: 'Hermann Meditech',
    logo: '/Brands/Hermann.png',
    relationship: 'Supported Brand Line',
    specialty: 'Surgical instruments',
    title: 'Hermann Meditech surgical instruments for Bahrain buyers',
    description: 'Hermann Meditech surgical instrument enquiries supported in Bahrain by Leading Trading Est with specification checks, quotation coordination and local follow-up.',
    intro: 'Public crawlable official detail for this brand is limited, so LTE keeps the page focused on the verified supply role: surgical instrument enquiries, item references, schedules and quotation support in Bahrain.',
    keywords: 'Hermann Meditech Bahrain, Hermann Meditech instruments, surgical instruments Bahrain',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }],
    focusAreas: [
      { title: 'Instrument schedule support', body: 'LTE can review surgical instrument lists by name, reference, size, pattern and intended procedure before quotation.' },
      { title: 'Bahrain procurement handling', body: 'Requests are handled through LTE for local follow-up, commercial coordination and delivery planning.' },
    ],
    faqs: [{ question: 'Can LTE quote Hermann Meditech instruments in Bahrain?', answer: 'Yes. Send the instrument name, reference, dimensions or schedule for specification review and quotation support.' }],
  },
  {
    slug: 'adc',
    name: 'ADC',
    logo: '/Brands/adc.png',
    relationship: 'Supported Brand Line',
    specialty: 'Stethoscopes, blood pressure, thermometry, EENT and diagnostic tools',
    title: 'ADC diagnostic devices and stethoscopes in Bahrain',
    description: 'ADC diagnostic device enquiries in Bahrain through Leading Trading Est, including stethoscopes, blood pressure measurement, thermometry, EENT and routine diagnostic instruments.',
    intro: 'American Diagnostic Corporation presents a diagnostic portfolio covering blood pressure measurement, EENT diagnostic instruments, laryngoscopes, penlights, pulse oximeters, stethoscopes, thermometry and vital signs monitors. LTE supports Bahrain quotation handling for relevant ADC requirements.',
    keywords: 'ADC Bahrain, ADC stethoscope Bahrain, ADC blood pressure monitor Bahrain, diagnostic devices Bahrain, EENT instruments Bahrain',
    categoryLinks: [{ label: 'Diagnostic Devices', path: '/categories/diagnostic-devices' }, { label: 'Medical Equipment', path: '/categories/medical-equipment' }],
    focusAreas: [
      { title: 'Blood pressure measurement', body: 'ADC lists aneroid, digital, multicuff, clock, cuff and accessory categories for blood pressure measurement.' },
      { title: 'Stethoscopes and diagnostic instruments', body: 'ADC product families include stethoscopes, EENT instruments, penlights, pulse oximeters, thermometry and vital sign tools.' },
      { title: 'Professional care environments', body: 'ADC positions its tools for healthcare professionals and institutions, with diagnostic design and warranty support emphasized publicly.' },
    ],
    faqs: [{ question: 'Does LTE support ADC diagnostic devices in Bahrain?', answer: 'Yes. Leading Trading Est supports ADC product enquiries and quotations for Bahrain buyers.' }],
  },
  {
    slug: 'rogin-dental',
    name: 'Rogin Dental',
    logo: '/Brands/rogin.png',
    relationship: 'Supported Brand Line',
    specialty: 'Dental supplies and endodontic consumables',
    title: 'Rogin Dental instruments and consumables in Bahrain',
    description: 'Rogin Dental supplies in Bahrain through Leading Trading Est, including endodontic, restorative and chairside dental supply enquiries.',
    intro: 'Public crawlable official detail for Rogin Dental is limited. LTE therefore keeps this profile tied to the dental supply role already represented in the LTE catalogue and supports buyer enquiries by product reference, clinical use and quantity.',
    keywords: 'Rogin Dental Bahrain, dental supplies Bahrain, endodontic files Bahrain, dental burs Bahrain',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [
      { title: 'Dental enquiry handling', body: 'LTE reviews dental product requirements by item name, reference, file type, bur type, pack size or clinical workflow.' },
      { title: 'Practice supply support', body: 'Requests are routed through LTE for local quotation, availability confirmation and repeat procurement support.' },
    ],
    faqs: [{ question: 'What Rogin Dental requests can LTE handle?', answer: 'LTE can handle Rogin Dental enquiries where buyers provide the product name, reference, quantity or intended dental use.' }],
  },
  {
    slug: 'zogear',
    name: 'Zogear',
    logo: '/Brands/Zogear.png',
    relationship: 'Supported Brand Line',
    specialty: 'Dental disposable, endodontic, orthodontic, rotary, laboratory and equipment categories',
    title: 'Zogear dental consumables in Bahrain',
    description: 'Zogear dental consumables supplied in Bahrain through Leading Trading Est, including disposable, endodontic, orthodontic, material, rotary, laboratory and equipment enquiries.',
    intro: 'Zogear presents itself as a dental product manufacturer and supplier with public product categories covering dental disposable, endodontic, dental material, orthodontic, dental rotary, dental laboratory, dental equipment, oral care and teeth model lines. LTE supports Bahrain dental buyers with quotation handling for relevant Zogear requirements.',
    keywords: 'Zogear Bahrain, Zogear dental supplies, dental disposable Bahrain, dental consumables Bahrain, dental equipment Bahrain',
    categoryLinks: [{ label: 'Dental', path: '/categories/dental' }],
    focusAreas: [
      { title: 'Dental disposable and chairside supplies', body: 'Zogear public categories include dental disposable and oral care lines for routine clinic consumption.' },
      { title: 'Endodontic, rotary and material categories', body: 'The brand lists endodontic, dental material and dental rotary product groups for practice workflows.' },
      { title: 'Laboratory and equipment coverage', body: 'Zogear also presents dental laboratory, dental equipment and teeth model categories.' },
    ],
    faqs: [{ question: 'Can dental clinics request Zogear quotations from LTE?', answer: 'Yes. Clinics can send the product name, quantity and delivery requirement for local quotation support.' }],
  },
  {
    slug: 'optima-cast',
    name: 'Optima Cast',
    logo: '/Brands/optimacast.png',
    relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic casting tape',
    title: 'Optima Cast orthopaedic casting tape in Bahrain',
    description: 'Optima Cast orthopaedic casting tape enquiries in Bahrain through Leading Trading Est for hospitals, clinics and rehabilitation providers.',
    intro: 'Public crawlable official detail for Optima Cast is limited. LTE keeps this page focused on the orthopaedic casting supply role and quotation handling by size, pack, colour and intended clinical use.',
    keywords: 'Optima Cast Bahrain, orthopedic casting tape Bahrain, orthopaedic supplies Bahrain',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [
      { title: 'Casting tape enquiries', body: 'LTE reviews orthopaedic casting tape requirements by width, roll quantity, pack configuration and facility demand.' },
      { title: 'Orthopaedic supply route', body: 'Requests are connected to the LTE orthopaedic and rehabilitation category for Bahrain quotation support.' },
    ],
    faqs: [{ question: 'Where can buyers request Optima Cast in Bahrain?', answer: 'Leading Trading Est supports Optima Cast enquiries and quotations for Bahrain healthcare buyers.' }],
  },
  {
    slug: 'osseous',
    name: 'Osseous',
    logo: '/Brands/osseous.png',
    relationship: 'Supported Brand Line',
    specialty: 'ENT surgical instruments',
    title: 'Osseous ENT instruments in Bahrain',
    description: 'Osseous ear, nose and throat instrument enquiries in Bahrain through Leading Trading Est with specialist specification and quotation support.',
    intro: 'Public crawlable official detail for Osseous is limited. LTE keeps the profile focused on ENT instrument supply support, reference review and Bahrain procurement handling.',
    keywords: 'Osseous Bahrain, ENT instruments Bahrain, ear nose throat instruments Bahrain, ENT surgical supplies Bahrain',
    categoryLinks: [{ label: 'Surgical Instruments', path: '/categories/surgical-instruments' }],
    focusAreas: [
      { title: 'ENT instrument schedules', body: 'LTE can review ENT instrument schedules by instrument name, reference, size and intended procedure.' },
      { title: 'Specialist quotation support', body: 'Requests are handled through LTE for local follow-up and quotation coordination.' },
    ],
    faqs: [{ question: 'Can LTE support Osseous ENT instrument schedules?', answer: 'Yes. Buyers can submit an instrument schedule or reference list for review and quotation.' }],
  },
  {
    slug: 'berger',
    name: 'Berger',
    logo: '/Brands/berger.jpg',
    relationship: 'Supported Brand Line',
    specialty: 'Orthopaedic supports, bracing and rehabilitation aids',
    title: 'Berger orthopaedic supports and braces in Bahrain',
    description: 'Berger orthopaedic supports, braces and rehabilitation aids in Bahrain through Leading Trading Est for clinical and recovery requirements.',
    intro: 'Public crawlable official detail for Berger is limited. LTE keeps the profile focused on orthopaedic support and bracing enquiries where size, body area and intended use must be clarified before quotation.',
    keywords: 'Berger orthopaedic Bahrain, orthopedic braces Bahrain, knee support Bahrain, back support Bahrain, rehabilitation supplies Bahrain',
    categoryLinks: [{ label: 'Orthopedic & Rehabilitation', path: '/categories/orthopedic-rehabilitation' }],
    focusAreas: [
      { title: 'Support and bracing enquiries', body: 'LTE reviews orthopaedic support requirements by body area, size range, support level and intended recovery use.' },
      { title: 'Rehabilitation procurement', body: 'Requests are connected to the LTE orthopaedic and rehabilitation category for Bahrain supply follow-up.' },
    ],
    faqs: [{ question: 'Does LTE supply Berger supports in Bahrain?', answer: 'LTE supports Berger orthopaedic and rehabilitation product enquiries for Bahrain buyers.' }],
  },
  {
    slug: 'bastos-viegas',
    name: 'Bastos Viegas',
    logo: '/Brands/bastosviegas.webp',
    relationship: 'Supported Brand Line',
    specialty: 'Non-active medical devices and surgical consumables',
    title: 'Bastos Viegas surgical consumables in Bahrain',
    description: 'Bastos Viegas surgical consumable enquiries in Bahrain through Leading Trading Est, including non-active medical device and procedure consumable requirements.',
    intro: 'Bastos Viegas publicly describes itself as a Portuguese producer and supplier of non-active medical devices, with European production and distribution across more than 90 countries. LTE supports Bahrain buyers with quotation handling for relevant Bastos Viegas consumable requirements.',
    keywords: 'Bastos Viegas Bahrain, surgical consumables Bahrain, non active medical devices Bahrain, surgical drapes Bahrain, medical gauze Bahrain',
    categoryLinks: [{ label: 'Sterile Surgical Consumables', path: '/categories/sterile-surgical-consumables' }, { label: 'Consumables & Disposables', path: '/categories/consumables-disposables' }],
    focusAreas: [
      { title: 'Non-active medical devices', body: 'Bastos Viegas identifies its core production around non-active medical devices with European production standards.' },
      { title: 'International distribution background', body: 'The company states its products are distributed in more than 90 countries across six continents.' },
      { title: 'Procedure consumable support', body: 'LTE handles Bahrain enquiries by item reference, pack configuration, quantity and intended clinical workflow.' },
    ],
    faqs: [{ question: 'Can LTE quote Bastos Viegas consumables?', answer: 'Yes. Send the item reference, pack requirement and quantity for Bahrain quotation support.' }],
  },
];

export const brandRoutes = [
  { path: '/brands', changefreq: 'weekly', priority: '0.86' },
  ...brandPages.map((brand) => ({
    path: `/brands/${brand.slug}`,
    changefreq: brand.featured || ['romsons', 'smi'].includes(brand.slug) ? 'weekly' : 'monthly',
    priority: brand.featured ? '0.86' : ['romsons', 'smi'].includes(brand.slug) ? '0.82' : '0.74',
  })),
];

export const getBrandPage = (slug) => brandPages.find((brand) => brand.slug === slug);
