export const SUPPORTED_LANGUAGES = {
  en: {
    code: 'en',
    label: 'English',
    shortLabel: 'EN',
    dir: 'ltr',
  },
  ar: {
    code: 'ar',
    label: 'العربية',
    shortLabel: 'AR',
    dir: 'rtl',
  },
};

export const AR_TRANSLATIONS = {
  'Home': 'الرئيسية',
  'Products': 'المنتجات',
  'Product': 'منتج',
  'Category': 'فئة',
  'Categories': 'الفئات',
  'Careers': 'الوظائف',
  'Contact': 'اتصل بنا',
  'Cart': 'السلة',
  'Orders': 'الطلبات',
  'Call': 'اتصال',
  'Call Us': 'اتصل بنا',
  'WhatsApp': 'واتساب',
  'Sign In': 'تسجيل الدخول',
  'Sign Up': 'إنشاء حساب',
  'Logout': 'تسجيل الخروج',
  'Browse All Categories': 'تصفح كل الفئات',
  'All Categories': 'كل الفئات',
  'Leading Trading Est': 'مؤسسة ليدنج تريدنج',
  'Medical, dental & industrial supply': 'توريد طبي وأسنان وصناعي',
  'Medstar': 'ميدستار',
  'Our own brand': 'علامتنا الخاصة',
  'Medstar is LTE’s own trusted medical supply brand, built around consistency, practical quality, and dependable market confidence.':
    'ميدستار هي علامة LTE الطبية الخاصة والموثوقة، مبنية على الاتساق والجودة العملية والثقة في السوق.',
  'Medstar supports day-to-day clinical purchasing with products selected for routine healthcare use, repeat procurement, and the service expectations of Bahrain medical and dental buyers.':
    'تدعم ميدستار المشتريات الطبية اليومية بمنتجات مختارة للاستخدام الصحي الروتيني والشراء المتكرر وتوقعات الخدمة لدى المشترين الطبيين وطب الأسنان في البحرين.',
  'LTE-owned brand with local accountability': 'علامة مملوكة لـ LTE مع مسؤولية محلية',
  'Recognized by buyers for dependable routine supply': 'معروفة لدى المشترين لتوريدها الروتيني الموثوق',
  'Supported by the same sourcing and delivery workflow behind LTE': 'مدعومة بنفس مسار التوريد والتسليم لدى LTE',
  'Medstar reflects LTE’s own brand commitment to practical quality, dependable availability, and market trust.':
    'تعكس ميدستار التزام علامة LTE الخاصة بالجودة العملية والتوفر الموثوق والثقة في السوق.',
  'LTE-owned medical supply brand': 'علامة توريد طبية مملوكة لـ LTE',
  'Medstar is part of Leading Trading Est’s own brand portfolio, developed to support recurring healthcare purchasing with products selected for practical use, steady availability, and dependable day-to-day performance.':
    'ميدستار جزء من محفظة العلامات الخاصة بمؤسسة ليدنج تريدنج، وتم تطويرها لدعم المشتريات الصحية المتكررة بمنتجات مختارة للاستخدام العملي والتوفر المستقر والأداء اليومي الموثوق.',
  'For Bahrain medical and dental buyers, Medstar strengthens LTE’s ability to provide a consistent local supply option backed by the same sourcing, quotation, delivery, and account support workflow behind the company.':
    'بالنسبة للمشترين الطبيين وطب الأسنان في البحرين، تعزز ميدستار قدرة LTE على توفير خيار توريد محلي ثابت مدعوم بنفس مسار التوريد وعروض الأسعار والتسليم ودعم الحسابات لدى الشركة.',
  'Own-brand accountability from a Bahrain-based supplier': 'مسؤولية علامة خاصة من مورد مقره البحرين',
  'Focused on reliable routine healthcare requirements': 'تركيز على المتطلبات الصحية الروتينية الموثوقة',
  'Supported by LTE’s local sales, accounts, and delivery teams': 'مدعومة بفرق المبيعات والحسابات والتسليم المحلية لدى LTE',
  'Request Quote': 'طلب عرض سعر',
  'Request Quotation': 'طلب عرض سعر',
  'Talk to Our Team': 'تحدث مع فريقنا',
  'Explore Categories': 'استكشف الفئات',
  'Product Catalog': 'كتالوج المنتجات',
  'A structured catalog for medical, dental, and industrial sourcing.': 'كتالوج منظم للتوريد الطبي وطب الأسنان والصناعي.',
  'Review the active catalog, narrow by category, and move directly into product pages designed for quotations, repeat procurement, and operational decision-making.': 'راجع الكتالوج المتاح، وضيّق النتائج حسب الفئة، وانتقل مباشرة إلى صفحات المنتجات المصممة لعروض الأسعار والشراء المتكرر واتخاذ القرار.',
  'products available': 'منتج متاح',
  'main categories': 'فئات رئيسية',
  'featured selections': 'اختيارات مميزة',
  'Catalog approach': 'طريقة الكتالوج',
  'Review products by category first when the requirement is operational rather than brand-specific.': 'ابدأ بمراجعة المنتجات حسب الفئة عندما يكون الاحتياج تشغيلياً وليس مرتبطاً بعلامة تجارية محددة.',
  'For most procurement teams, category-led browsing is the fastest way to move from requirement to shortlist.': 'بالنسبة لمعظم فرق المشتريات، التصفح حسب الفئة هو أسرع طريق للانتقال من الاحتياج إلى القائمة المختصرة.',
  'Quotation workflow': 'مسار عرض السعر',
  'Use the product pages to confirm specifications, variant structure, and quotation support.': 'استخدم صفحات المنتجات لتأكيد المواصفات والخيارات ودعم عرض السعر.',
  'Where sizing, type selection, or documentation matters, the product detail page provides the clearer next step.': 'عندما تكون المقاسات أو الأنواع أو المستندات مهمة، توفر صفحة تفاصيل المنتج الخطوة التالية بوضوح.',
  'Repeat procurement': 'الشراء المتكرر',
  'Built for recurring demand across healthcare, dental, safety, and facility support categories.': 'مصمم للاحتياجات المتكررة في فئات الرعاية الصحية وطب الأسنان والسلامة ودعم المنشآت.',
  'The LTE catalog is organized to support both one-time sourcing needs and repeat account purchasing.': 'تم تنظيم كتالوج LTE لدعم احتياجات التوريد لمرة واحدة وعمليات الشراء المتكررة للحسابات.',
  'Compliance support': 'دعم الامتثال',
  'Documentation and specification checks before quotation.': 'مراجعة المستندات والمواصفات قبل عرض السعر.',
  'Local response': 'استجابة محلية',
  'Bahrain-based team for healthcare and industrial sourcing.': 'فريق مقره البحرين للتوريد الصحي والصناعي.',
  'Repeat buying': 'شراء متكرر',
  'Catalog structure built for recurring procurement workflows.': 'هيكل كتالوج يدعم مسارات المشتريات المتكررة.',
  'Search products by name, brand, or SKU': 'ابحث باسم المنتج أو العلامة أو الرمز',
  'Sort: Featured': 'الترتيب: المميز',
  'Sort: Name': 'الترتيب: الاسم',
  'Sort: Price': 'الترتيب: السعر',
  'Apply': 'تطبيق',
  'Reset Filters': 'إعادة ضبط الفلاتر',
  'Updating catalog...': 'جار تحديث الكتالوج...',
  'shown on this page': 'معروض في هذه الصفحة',
  'Unavailable': 'غير متاح',
  'Product catalog unavailable': 'كتالوج المنتجات غير متاح',
  'We could not load the product catalog right now.': 'تعذر تحميل كتالوج المنتجات حالياً.',
  'Try Again': 'حاول مرة أخرى',
  'No Results': 'لا توجد نتائج',
  'No products found': 'لم يتم العثور على منتجات',
  'The current filters returned no products. Broaden the search or reset filters.': 'لم تُظهر الفلاتر الحالية أي منتجات. وسّع البحث أو أعد ضبط الفلاتر.',
  'Featured': 'مميز',
  'Sourcing item': 'منتج توريد',
  'Open the product to review variants, specifications, and request options.': 'افتح المنتج لمراجعة الخيارات والمواصفات وطلبات السعر.',
  'Product details, variants, and quotation support for': 'تفاصيل المنتج وخياراته ودعم عرض السعر لفئة',
  'Contact LTE for specifications, availability, and quotation support for this catalog item.':
    'تواصل مع LTE للحصول على المواصفات والتوفر ودعم عرض السعر لهذا المنتج.',
  'Quote on request': 'السعر عند الطلب',
  'View details': 'عرض التفاصيل',
  'Prev': 'السابق',
  'Next': 'التالي',
  'Page': 'صفحة',
  'of': 'من',
  'Product unavailable': 'المنتج غير متاح',
  'We could not load the selected product right now.': 'تعذر تحميل المنتج المحدد حالياً.',
  'Return to Shop': 'العودة إلى المتجر',
  'Image available on request': 'الصورة متاحة عند الطلب',
  'Contact our team for visuals, specifications, and availability details.': 'تواصل مع فريقنا للحصول على الصور والمواصفات وتفاصيل التوفر.',
  'Catalog product': 'منتج من الكتالوج',
  'Contact our team for product specifications, availability, and commercial support.': 'تواصل مع فريقنا للحصول على مواصفات المنتج والتوفر والدعم التجاري.',
  'Procurement use': 'استخدامات المشتريات',
  'Review the product structure before moving into quotation or cart handling.': 'راجع بنية المنتج قبل الانتقال إلى عرض السعر أو السلة.',
  'Where products depend on type, size, brand, or commercial fit, the detail page gives the clearest next step.': 'عندما يعتمد المنتج على النوع أو المقاس أو العلامة أو الملاءمة التجارية، توضح صفحة التفاصيل الخطوة التالية.',
  'Support path': 'مسار الدعم',
  'LTE can assist with specification fit, availability, and repeat-order planning.': 'يمكن لفريق LTE المساعدة في ملاءمة المواصفات والتوفر وتخطيط الطلبات المتكررة.',
  'Use WhatsApp, direct enquiry, or quotation handling when the requirement needs confirmation before purchase.': 'استخدم واتساب أو الاستفسار المباشر أو طلب عرض السعر عند الحاجة لتأكيد المتطلبات قبل الشراء.',
  'Success': 'تم بنجاح',
  'Notice': 'تنبيه',
  'Current price': 'السعر الحالي',
  'WhatsApp Quote': 'عرض سعر عبر واتساب',
  'Choose Type': 'اختر النوع',
  'Choose Size': 'اختر المقاس',
  'Quantity': 'الكمية',
  'Add to Cart': 'إضافة إلى السلة',
  'Specifications': 'المواصفات',
  'Specification': 'المواصفة',
  'Also in this category': 'منتجات أخرى في هذه الفئة',
  'Related products in the same operational category': 'منتجات ذات صلة في نفس الفئة التشغيلية',
  'Browse Category': 'تصفح الفئة',
  'Our Categories': 'فئاتنا',
  'Browse LTE’s medical, dental, and industrial categories.': 'تصفح فئات LTE الطبية وطب الأسنان والصناعية.',
  "Browse LTE's medical, dental, and industrial categories.": 'تصفح فئات LTE الطبية وطب الأسنان والصناعية.',
  'Browse LTE&apos;s medical, dental, and industrial categories.': 'تصفح فئات LTE الطبية وطب الأسنان والصناعية.',
  'Review the main groups first, then open the relevant category to find the right department or supply area faster.': 'راجع المجموعات الرئيسية أولاً، ثم افتح الفئة المناسبة للوصول إلى القسم أو مجال التوريد بسرعة.',
  'Search categories, departments, or supply types': 'ابحث في الفئات أو الأقسام أو أنواع التوريد',
  'active categories': 'فئة نشطة',
  'with descriptions': 'بها أوصاف',
  'Loading': 'جار التحميل',
  'Preparing the category catalog': 'جار تجهيز كتالوج الفئات',
  'We’re pulling the current category structure and matching assets.': 'نقوم بتحميل هيكل الفئات الحالي والأصول المرتبطة به.',
  'Category catalog not available': 'كتالوج الفئات غير متاح',
  'We could not load the category catalog right now.': 'تعذر تحميل كتالوج الفئات حالياً.',
  'No Match': 'لا يوجد تطابق',
  'No categories match that search': 'لا توجد فئات تطابق هذا البحث',
  'No categories are available yet.': 'لا توجد فئات متاحة حالياً.',
  'Clear Search': 'مسح البحث',
  'Structured browsing': 'تصفح منظم',
  'Start with the main operating group, then open the relevant category directly.': 'ابدأ بالمجموعة التشغيلية الرئيسية، ثم افتح الفئة المناسبة مباشرة.',
  'The catalog now stays at the main-category level so visitors can move into the right department faster.': 'يبقى الكتالوج على مستوى الفئات الرئيسية حتى يتمكن الزوار من الوصول للقسم المناسب بسرعة.',
  'Practical filtering': 'فلترة عملية',
  'Use the search bar to narrow by department, supply type, or procurement purpose.': 'استخدم شريط البحث للتضييق حسب القسم أو نوع التوريد أو غرض الشراء.',
  'Searches look across the full category catalog, making it easier to locate the correct supply path.': 'يبحث النظام في كتالوج الفئات بالكامل لتسهيل الوصول إلى مسار التوريد الصحيح.',
  'Quotation support': 'دعم عروض الأسعار',
  'Open a category to review its products, then contact LTE for sourcing guidance.': 'افتح الفئة لمراجعة منتجاتها، ثم تواصل مع LTE للحصول على إرشاد التوريد.',
  'When you need help choosing the right section, the team can guide the next step directly.': 'عند الحاجة للمساعدة في اختيار القسم الصحيح، يمكن للفريق توجيهك مباشرة.',
  'available': 'متاحة',
  'Select a main category to review the products available inside that operating group.': 'اختر فئة رئيسية لمراجعة المنتجات المتاحة داخل تلك المجموعة التشغيلية.',
  'Main Category': 'فئة رئيسية',
  'Open': 'فتح',
  'Browse the products available inside this main category.': 'تصفح المنتجات المتاحة داخل هذه الفئة الرئيسية.',
  'more': 'أخرى',
  'GET IN TOUCH': 'تواصل معنا',
  "We're here to assist you!": 'نحن هنا لمساعدتك!',
  'Name': 'الاسم',
  'Email address': 'البريد الإلكتروني',
  'Phone number': 'رقم الهاتف',
  'Message': 'الرسالة',
  'I allow this website to store my submission so they can respond to my inquiry.': 'أسمح لهذا الموقع بحفظ طلبي حتى يتمكنوا من الرد على استفساري.',
  'Sending…': 'جار الإرسال...',
  'Submit': 'إرسال',
  'Could not submit your inquiry. Please try again.': 'تعذر إرسال استفسارك. يرجى المحاولة مرة أخرى.',
  'Thank you! We will get back to you shortly.': 'شكراً لك! سنتواصل معك قريباً.',
  'Network error. Please check your connection and try again.': 'حدث خطأ في الشبكة. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
  'Get in touch': 'تواصل معنا',
  'Location': 'الموقع',
  'Hours': 'ساعات العمل',
  'Reach Out': 'تواصل',
  'Direct': 'مباشر',
  'WhatsApp support': 'دعم واتساب',
  'Office': 'المكتب',
  'Sat – Thu: 8:00am – 4:00pm': 'السبت - الخميس: 8:00 صباحاً - 4:00 مساءً',
  'Supply support built for clinical, dental, and operational teams.': 'دعم توريد مصمم للفرق الطبية وفرق طب الأسنان والتشغيل.',
  'Trusted sourcing, dependable manufacturer access, and responsive account support for organizations across Bahrain.': 'توريد موثوق، ووصول إلى المصنعين، ودعم سريع للحسابات للمؤسسات في البحرين.',
  'All rights reserved.': 'جميع الحقوق محفوظة.',
  'Email or Username': 'البريد الإلكتروني أو اسم المستخدم',
  'Enter your email or username': 'أدخل بريدك الإلكتروني أو اسم المستخدم',
  'Password': 'كلمة المرور',
  'Signing in...': 'جار تسجيل الدخول...',
  'New here?': 'جديد هنا؟',
  'Create an account': 'أنشئ حساباً',
  'Create Account': 'إنشاء حساب',
  'Full Name': 'الاسم الكامل',
  'Username': 'اسم المستخدم',
  'Choose a username': 'اختر اسم مستخدم',
  'Email': 'البريد الإلكتروني',
  'Phone': 'الهاتف',
  'Subscribe to updates and offers': 'الاشتراك في التحديثات والعروض',
  'Creating account...': 'جار إنشاء الحساب...',
  'Already have an account?': 'لديك حساب بالفعل؟',
  'Sign in': 'تسجيل الدخول',
  'Choose a size before adding to cart': 'اختر المقاس قبل الإضافة إلى السلة',
  'This product uses size-level selection, so we need that choice first.': 'هذا المنتج يتطلب اختيار المقاس، لذلك نحتاج إلى تحديده أولاً.',
  'Could not add product to cart': 'تعذرت إضافة المنتج إلى السلة',
  'Please try again in a moment.': 'يرجى المحاولة بعد قليل.',
  'Added to cart': 'تمت الإضافة إلى السلة',
  'The product was added successfully. You can continue browsing or review the cart now.': 'تمت إضافة المنتج بنجاح. يمكنك متابعة التصفح أو مراجعة السلة الآن.',
  'Preparing product details': 'جار تجهيز تفاصيل المنتج',
  'We’re loading the gallery, pricing, specifications, and related products.': 'نقوم بتحميل الصور والأسعار والمواصفات والمنتجات ذات الصلة.',
  'Product not available': 'المنتج غير متاح',
  'The selected product could not be loaded.': 'تعذر تحميل المنتج المحدد.',
  'Open Cart': 'فتح السلة',
  'Your Cart': 'سلتك',
  'Loading cart...': 'جار تحميل السلة...',
  'Your cart is empty.': 'سلتك فارغة.',
  'Browse products': 'تصفح المنتجات',
  'No image': 'لا توجد صورة',
  'SKU': 'رمز المنتج',
  'Line total': 'إجمالي السطر',
  'Remove': 'إزالة',
  'Summary': 'الملخص',
  'Subtotal': 'المجموع الفرعي',
  'Shipping': 'الشحن',
  'Total': 'الإجمالي',
  'Proceed to Checkout': 'المتابعة إلى الدفع',
  'Checkout': 'الدفع',
  'Shipping Details': 'تفاصيل الشحن',
  'Address Line 1': 'العنوان 1',
  'Address Line 2': 'العنوان 2',
  'City': 'المدينة',
  'Country': 'الدولة',
  'Postal Code': 'الرمز البريدي',
  'Payment': 'الدفع',
  'Cash on Delivery': 'الدفع عند الاستلام',
  'Bank Transfer': 'تحويل بنكي',
  'Tap Card Payment': 'الدفع بالبطاقة عبر Tap',
  'Bank transfer details will be shared after placing the order.': 'سيتم مشاركة تفاصيل التحويل البنكي بعد تقديم الطلب.',
  'Tap is not configured yet. Please use COD or Bank Transfer.': 'لم يتم تفعيل Tap بعد. يرجى استخدام الدفع عند الاستلام أو التحويل البنكي.',
  'Notes': 'ملاحظات',
  'Placing order...': 'جار تقديم الطلب...',
  'Place Order': 'تقديم الطلب',
  'Order Summary': 'ملخص الطلب',
  'Qty': 'الكمية',
  'Tap is not available': 'خدمة Tap غير متاحة',
  'Checkout failed': 'فشل إتمام الطلب',
  'My Orders': 'طلباتي',
  'Loading orders...': 'جار تحميل الطلبات...',
  'No orders yet.': 'لا توجد طلبات بعد.',
  'Session expired. Please sign in again.': 'انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.',
  'Failed to download invoice': 'تعذر تحميل الفاتورة',
  'Download Invoice': 'تحميل الفاتورة',
  'Shop again': 'تسوق مرة أخرى',
  'Nothing matched': 'لم يطابق البحث',
  'Try a broader term or browse the full catalog.': 'جرّب مصطلحاً أوسع أو تصفح الكتالوج الكامل.',
  'Request a Quote': 'طلب عرض سعر',
  'Leading Trading Est. | Bahrain': 'مؤسسة ليدنج تريدنج | البحرين',
  'Reliable medical and industrial supply with disciplined sourcing, quality assurance, and dependable local support.':
    'توريد طبي وصناعي موثوق مع توريد منظم، وضمان جودة، ودعم محلي يعتمد عليه.',
  'Leading Trading Est. supports hospitals, clinics, practices, and operational teams across Bahrain with structured sourcing, established supplier relationships, and coordinated delivery execution.':
    'تدعم مؤسسة ليدنج تريدنج المستشفيات والعيادات والممارسات والفرق التشغيلية في البحرين من خلال توريد منظم وعلاقات موردين راسخة وتنفيذ منسق للتسليم.',
  'NHRA-Approved': 'معتمد من الهيئة الوطنية لتنظيم المهن والخدمات الصحية',
  'Medical and industrial sourcing': 'توريد طبي وصناعي',
  'Dependable Bahrain-based support': 'دعم موثوق من البحرين',
  'How LTE creates value': 'كيف تقدم LTE القيمة',
  'Our business model combines supplier access, quality review, logistics planning, and customer follow-through.':
    'يجمع نموذج عملنا بين الوصول إلى الموردين ومراجعة الجودة وتخطيط الخدمات اللوجستية والمتابعة مع العملاء.',
  'LTE is structured to support procurement decisions with better supplier visibility, clearer specification control, coordinated logistics, and responsive account management.':
    'تم تنظيم LTE لدعم قرارات المشتريات من خلال رؤية أفضل للموردين، وضبط أوضح للمواصفات، ولوجستيات منسقة، وإدارة حسابات سريعة الاستجابة.',
  'Workflow': 'سير العمل',
  'A clear operating workflow supports every enquiry, quotation, procurement decision, and delivery commitment.':
    'يدعم سير عمل تشغيلي واضح كل استفسار وعرض سعر وقرار شراء والتزام تسليم.',
  'Each requirement moves through review, sourcing, procurement alignment, logistics coordination, and delivery support so the customer receives a more dependable service path.':
    'يمر كل احتياج عبر المراجعة والتوريد ومواءمة المشتريات وتنسيق اللوجستيات ودعم التسليم ليحصل العميل على مسار خدمة أكثر موثوقية.',
  'Sector focus': 'تركيز القطاعات',
  'One operating model supporting two sectors with different technical needs but the same requirement for dependable execution.':
    'نموذج تشغيلي واحد يدعم قطاعين باحتياجات فنية مختلفة، مع نفس الحاجة إلى تنفيذ موثوق.',
  'LTE serves medical and industrial buyers through the same standards of supplier assessment, quality review, logistics coordination, and local customer support.':
    'تخدم LTE المشترين في القطاعين الطبي والصناعي بنفس معايير تقييم الموردين ومراجعة الجودة وتنسيق اللوجستيات والدعم المحلي.',
  'Trusted brands and institutions': 'علامات ومؤسسات موثوقة',
  'Our supplier network and institutional customer base reflect the standards we are expected to maintain.':
    'تعكس شبكة موردينا وقاعدة عملائنا المؤسسية المعايير التي نتوقع الحفاظ عليها.',
  'LTE works with selected manufacturers and supports institutions that require reliability, product quality, and professional service standards.':
    'تعمل LTE مع مصنعين مختارين وتدعم مؤسسات تحتاج إلى الاعتمادية وجودة المنتجات ومعايير الخدمة المهنية.',
  'Core categories': 'الفئات الأساسية',
  'Supply categories supporting clinical, dental, and industrial operations.':
    'فئات توريد تدعم العمليات السريرية وطب الأسنان والصناعية.',
  'Browse all categories': 'تصفح كل الفئات',
  'Explore category': 'استكشف الفئة',
  'Selected product highlights': 'منتجات مختارة',
  'A focused look at representative products across the LTE catalog.':
    'نظرة مركزة على منتجات تمثل كتالوج LTE.',
  'Product spotlight': 'منتج مميز',
  'LTE catalog': 'كتالوج LTE',
  'LTE selection': 'اختيار LTE',
  'Open product': 'فتح المنتج',
  'Why LTE': 'لماذا LTE',
  'Next step': 'الخطوة التالية',
  'Learn More About LTE': 'اعرف المزيد عن LTE',
  'Category not available': 'الفئة غير متاحة',
  'Category not found': 'لم يتم العثور على الفئة',
  'Failed to load category details': 'تعذر تحميل تفاصيل الفئة',
  'The category you requested could not be found.': 'تعذر العثور على الفئة المطلوبة.',
  'Category Focus': 'تركيز الفئة',
  'Review the products listed in this category and contact our team for specification guidance, availability, and quotation support.':
    'راجع المنتجات المدرجة في هذه الفئة وتواصل مع فريقنا للحصول على إرشاد المواصفات والتوفر ودعم عرض السعر.',
  'products currently listed': 'منتجات مدرجة حالياً',
  'brands represented': 'علامات ممثلة',
  'Request sourcing support': 'طلب دعم التوريد',
  'Subcategories inside': 'فئات فرعية داخل',
  'Open a subcategory to narrow the catalog further, or keep scrolling to review products across the full group.':
    'افتح فئة فرعية لتضييق الكتالوج أكثر، أو تابع التمرير لمراجعة المنتجات في المجموعة كاملة.',
  'Subcategory': 'فئة فرعية',
  'Open this subcategory to review the dedicated product set.': 'افتح هذه الفئة الفرعية لمراجعة مجموعة المنتجات الخاصة بها.',
  'Products across this main category': 'منتجات ضمن هذه الفئة الرئيسية',
  'Products in this category': 'منتجات في هذه الفئة',
  'Filter by name, brand, description, or SKU to narrow the relevant products quickly.':
    'فلتر حسب الاسم أو العلامة أو الوصف أو رمز المنتج لتضييق المنتجات المناسبة بسرعة.',
  'Search products in this category': 'ابحث عن منتجات في هذه الفئة',
  'Empty Category': 'فئة فارغة',
  'No products in this category yet': 'لا توجد منتجات في هذه الفئة حالياً',
  'This category is live, but the product catalog has not been populated yet.':
    'هذه الفئة مفعلة، لكن لم تتم إضافة منتجات إليها بعد.',
  'No products match that search': 'لا توجد منتجات تطابق هذا البحث',
  'Nothing in': 'لا يوجد شيء في',
  'matched': 'يطابق',
  'Try a broader keyword.': 'جرّب كلمة بحث أوسع.',
  'Catalog item': 'منتج من الكتالوج',
  'Open the product to review specifications, available variants, and quotation options.':
    'افتح المنتج لمراجعة المواصفات والخيارات المتاحة وخيارات عرض السعر.',
  'Join Our Team': 'انضم إلى فريقنا',
  'We’re always looking for passionate people to help improve healthcare access. Share your details and CV and we’ll get back to you.':
    'نبحث دائماً عن أشخاص شغوفين للمساهمة في تحسين الوصول إلى الرعاية الصحية. شارك بياناتك وسيرتك الذاتية وسنتواصل معك.',
  'Application Sent': 'تم إرسال الطلب',
  'Application received': 'تم استلام الطلب',
  'Thank you for your application. Our team will contact you soon.': 'شكراً لتقديمك. سيتواصل معك فريقنا قريباً.',
  'Submission Error': 'خطأ في الإرسال',
  'We couldn’t send your application': 'تعذر إرسال طلبك',
  'Failed to submit application. Please try again.': 'تعذر إرسال الطلب. يرجى المحاولة مرة أخرى.',
  'Phone Number': 'رقم الهاتف',
  'Nationality': 'الجنسية',
  'Upload CV': 'تحميل السيرة الذاتية',
  'Choose File': 'اختر ملفاً',
  'No file chosen': 'لم يتم اختيار ملف',
  'Sending Application...': 'جار إرسال الطلب...',
  'Submit Application': 'إرسال الطلب',
  "We've received your request for": 'استلمنا طلبك بخصوص',
  'Our team will get back to you shortly.': 'سيتواصل معك فريقنا قريباً.',
  'Interested in': 'مهتم بـ',
  'About Leading Trading Est': 'عن مؤسسة ليدنج تريدنج',
  'Supporting procurement in Bahrain with disciplined sourcing, quality assurance, and dependable delivery coordination.':
    'دعم المشتريات في البحرين من خلال توريد منظم، وضمان جودة، وتنسيق تسليم موثوق.',
  'Since 2012, Leading Trading Est has supported organizations in Bahrain across medical, dental, industrial, and safety requirements with a focus on product quality, service reliability, and professional execution.':
    'منذ عام 2012، دعمت مؤسسة ليدنج تريدنج المؤسسات في البحرين ضمن الاحتياجات الطبية وطب الأسنان والصناعية والسلامة، مع التركيز على جودة المنتجات واعتمادية الخدمة والتنفيذ المهني.',
  'Operating profile': 'الملف التشغيلي',
  'Supplier-led sourcing, structured procurement, and dependable operational follow-through.':
    'توريد قائم على الموردين، ومشتريات منظمة، ومتابعة تشغيلية موثوقة.',
  'Our business model combines supplier access, quality review, procurement discipline, logistics planning, and local account support under one coordinated operating workflow.':
    'يجمع نموذج عملنا بين الوصول إلى الموردين ومراجعة الجودة وانضباط المشتريات وتخطيط اللوجستيات ودعم الحسابات محلياً ضمن سير عمل تشغيلي منسق.',
  'company foundation': 'تأسيس الشركة',
  'Medical': 'طبي',
  'Industrial': 'صناعي',
  'clinical and equipment supply': 'توريد سريري ومعدات',
  'safety and operational support': 'دعم السلامة والتشغيل',
  'Company profile': 'ملف الشركة',
  'A Bahrain-based supply business built around continuity, accountability, and service reliability.':
    'شركة توريد بحرينية مبنية على الاستمرارية والمساءلة واعتمادية الخدمة.',
  'What defines the company': 'ما يميز الشركة',
  'Leadership': 'القيادة',
  'Leadership that sets the standard for quality, coordination, and long-term customer confidence.':
    'قيادة تضع معيار الجودة والتنسيق وثقة العملاء على المدى الطويل.',
  'Message from leadership': 'رسالة من القيادة',
  'Team structure': 'هيكل الفريق',
  'A team structure built around leadership, commercial coordination, administrative control, and delivery execution.':
    'هيكل فريق قائم على القيادة والتنسيق التجاري والضبط الإداري وتنفيذ التسليم.',
  'A team structure built around leadership, commercial coordination, administrative control, delivery execution, technology, and digital visibility.':
    'هيكل فريق قائم على القيادة والتنسيق التجاري والضبط الإداري وتنفيذ التسليم والتقنية والحضور الرقمي.',
  'Managing Director & CEO': 'المدير العام والرئيس التنفيذي',
  'Sets the company’s strategic direction, strengthens supplier relationships, and maintains the service, quality, and operating standards clients expect from LTE.':
    'يحدد التوجه الاستراتيجي للشركة، ويعزز علاقات الموردين، ويحافظ على معايير الخدمة والجودة والتشغيل التي يتوقعها العملاء من LTE.',
  'Accounts & HR': 'الحسابات والموارد البشرية',
  'Operational control and internal continuity': 'الضبط التشغيلي والاستمرارية الداخلية',
  'Supports financial discipline, internal administration, staff coordination, and the controls required to keep day-to-day operations stable, accurate, and dependable.':
    'يدعم الانضباط المالي والإدارة الداخلية وتنسيق الموظفين والضوابط اللازمة للحفاظ على استقرار ودقة واعتمادية العمليات اليومية.',
  'Sales Department': 'قسم المبيعات',
  'Customer-facing commercial execution': 'تنفيذ تجاري موجه للعملاء',
  'Manages enquiries, quotations, account follow-up, and commercial coordination so customer requirements are converted into suitable sourcing and procurement decisions.':
    'يدير الاستفسارات وعروض الأسعار ومتابعة الحسابات والتنسيق التجاري لتحويل متطلبات العملاء إلى قرارات توريد ومشتريات مناسبة.',
  'Delivery Team': 'فريق التسليم',
  'Final-mile fulfillment and handoff': 'تنفيذ التسليم النهائي والتسليم للعميل',
  'Coordinates dispatch and handover so confirmed orders are delivered on time, in the correct condition, and with the follow-through required for repeat business.':
    'ينسق الإرسال والتسليم لضمان وصول الطلبات المؤكدة في الوقت المحدد وبالحالة الصحيحة مع المتابعة المطلوبة للأعمال المتكررة.',
  'IT Department': 'قسم تقنية المعلومات',
  'Digital systems, security, and operational continuity': 'الأنظمة الرقمية والأمن والاستمرارية التشغيلية',
  'Maintains the website, admin tools, data workflows, and technical controls that support secure operations, reliable access, and smoother customer-facing service.':
    'يحافظ على الموقع وأدوات الإدارة ومسارات البيانات والضوابط التقنية التي تدعم التشغيل الآمن والوصول الموثوق والخدمة الرقمية الأكثر سلاسة للعملاء.',
  'Digital Marketing': 'التسويق الرقمي',
  'Brand visibility and customer communication': 'ظهور العلامة والتواصل مع العملاء',
  'Supports LTE’s digital presence, social channels, campaign communication, and product visibility so customers can discover the company and stay connected more easily.':
    'يدعم الحضور الرقمي لـ LTE وقنوات التواصل والحملات وظهور المنتجات حتى يتمكن العملاء من اكتشاف الشركة والبقاء على تواصل بسهولة أكبر.',
  'Quality commitment': 'الالتزام بالجودة',
  'Working relationship': 'علاقة العمل',
};

export const CATEGORY_AR_TRANSLATIONS = {
  'Medical Equipment': 'المعدات الطبية',
  'Anesthesia & Respiratory': 'التخدير والتنفس',
  'Laboratory': 'المختبر',
  'CSSD': 'قسم التعقيم المركزي',
  'Surgical Instruments': 'الأدوات الجراحية',
  'Consumables & Disposables': 'المستهلكات والمواد ذات الاستخدام الواحد',
  'Examination & General Disposable': 'الفحص والمستهلكات العامة',
  'Injection & IV Disposable': 'الحقن ومستهلكات الوريد',
  'PPE Masks & Shields': 'أقنعة وواقيات الحماية الشخصية',
  'PPE Gloves': 'قفازات الحماية الشخصية',
  'Gowns, Drapes & Covers': 'الأثواب والستائر والأغطية',
  'Wound Dressings & Gauze': 'ضمادات الجروح والشاش',
  'Medical Tapes & Bandages': 'الأشرطة الطبية والضمادات',
  'Skin Prep & First Aid': 'تحضير الجلد والإسعافات الأولية',
  'Sutures': 'الخيوط الجراحية',
  'Orthopedic & Rehabilitation': 'العظام وإعادة التأهيل',
  'Hospital Furniture & Utilities': 'أثاث ومستلزمات المستشفيات',
  'Urology': 'المسالك البولية',
  'Dental': 'طب الأسنان',
  'Industrial & Safety': 'الصناعة والسلامة',
};

export const CATEGORY_DESCRIPTION_AR_TRANSLATIONS = {
  'Clinical devices and room equipment for diagnostics, monitoring, suction, mobility support, and daily care delivery.':
    'أجهزة سريرية ومعدات غرف للتشخيص والمراقبة والشفط ودعم الحركة والرعاية اليومية.',
  'Airway, oxygen therapy, breathing circuit, suction, nebulization, and resuscitation products for respiratory care.':
    'منتجات مجرى الهواء والعلاج بالأكسجين ودوائر التنفس والشفط والتبخير والإنعاش للرعاية التنفسية.',
  'Laboratory consumables and diagnostic support products for sample collection, testing, recording, and routine clinical checks.':
    'مستهلكات مختبرية ومنتجات دعم تشخيصي لجمع العينات والاختبارات والتسجيل والفحوصات السريرية الروتينية.',
  'Sterilization packaging, process indicators, cleaning consumables, and clinical waste handling products for CSSD workflows.':
    'تغليف التعقيم ومؤشرات العمليات ومستهلكات التنظيف ومنتجات التعامل مع النفايات الطبية لمسارات التعقيم المركزي.',
  'Reusable and disposable surgical, examination, cutting, marking, and procedure-support instruments.':
    'أدوات جراحية وفحص وقطع وتعليم ودعم الإجراءات، قابلة لإعادة الاستخدام أو للاستخدام الواحد.',
  'Daily-use disposable clinical supplies including PPE, IV accessories, dressings, sutures, and examination items.':
    'مستلزمات سريرية يومية للاستخدام الواحد تشمل معدات الحماية وملحقات الوريد والضمادات والخيوط ومواد الفحص.',
  'Orthopedic supports, braces, casting materials, bandages, and rehabilitation products for mobility and recovery support.':
    'دعامات وجبائر ومواد تجبير وضمادات ومنتجات إعادة تأهيل لدعم الحركة والتعافي.',
  'Workplace safety products for staff protection and operational safety in healthcare and industrial environments.':
    'منتجات سلامة مكان العمل لحماية العاملين والسلامة التشغيلية في البيئات الصحية والصناعية.',
};

export const translateText = (language, value, fallback = value) => {
  if (language !== 'ar') return fallback;
  return AR_TRANSLATIONS[value] || fallback;
};

export const translateCategoryName = (language, value) => {
  if (language !== 'ar') return value;
  return CATEGORY_AR_TRANSLATIONS[value] || value;
};

export const translateCategoryDescription = (language, value) => {
  if (language !== 'ar') return value;
  return CATEGORY_DESCRIPTION_AR_TRANSLATIONS[value] || value;
};
